from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from threat_knowledge import format_mitre_attack, generate_top_recommendations


EXPORTS_DIR = Path(__file__).parent / "exports"
EXPORTS_DIR.mkdir(exist_ok=True)

SEVERITY_MARKERS = {
    "Critical": "[CRITICAL]",
    "High": "[HIGH]",
    "Medium": "[MEDIUM]",
    "Low": "[LOW]",
    "Informational": "[INFO]",
    "Clean": "[CLEAN]",
}

OWASP_LINKS = {
    "A01:2021": "https://owasp.org/Top10/A01_2021-Broken_Access_Control/",
    "A02:2021": "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/",
    "A03:2021": "https://owasp.org/Top10/A03_2021-Injection/",
    "A04:2021": "https://owasp.org/Top10/A04_2021-Insecure_Design/",
    "A05:2021": "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/",
    "A06:2021": "https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/",
    "A07:2021": "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/",
    "A08:2021": "https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/",
    "A09:2021": "https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/",
    "A10:2021": "https://owasp.org/Top10/A10_2021-Server_Side_Request_Forgery/",
}


def build_text_report(
    analysis_type: str,
    input_name: str,
    risk_score: int,
    severity_label: str,
    findings: list[dict[str, Any]],
    executive_summary: dict | None = None,
    language: str = "en",
    rule_findings: list[dict[str, Any]] | None = None,
    attack_timeline: list[dict[str, Any]] | None = None,
    top_recommendations: list[str] | None = None,
) -> str:
    lines: list[str] = []
    sep = "=" * 78
    thin = "-" * 78
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    marker = SEVERITY_MARKERS.get(severity_label, "[WARN]")
    findings = findings or []
    rule_findings = rule_findings or []
    top_recommendations = top_recommendations or generate_top_recommendations(findings)

    lines.append(sep)
    lines.append("SENTINELAI SECURITY ANALYSIS REPORT")
    lines.append(sep)
    lines.append(f"Generated     : {now}")
    lines.append(f"Analysis Type : {analysis_type.upper()}")
    lines.append(f"Source        : {input_name}")
    lines.append(f"Risk Score    : {risk_score}/100")
    lines.append(f"Severity      : {marker} {severity_label}")
    lines.append(f"Findings      : {len(findings)}")
    lines.append(f"Rule Signals  : {len(rule_findings)}")
    lines.append(sep)
    lines.append("")

    _append_executive_summary(lines, executive_summary or {}, severity_label)
    _append_top_recommendations(lines, top_recommendations)
    _append_attack_timeline(lines, attack_timeline or [])
    _append_rule_pre_scan(lines, rule_findings)
    _append_detailed_findings(lines, findings)
    _append_references(lines, findings, rule_findings)

    lines.append(sep)
    lines.append("DISCLAIMER")
    lines.append(thin)
    lines.append("This report was generated by SentinelAI for educational and defensive")
    lines.append("security purposes only. Findings are based on AI analysis and rule-based")
    lines.append("detection and may include false positives. Validate findings before")
    lines.append("production changes or incident response actions.")
    lines.append(sep)

    return "\n".join(lines)


def save_text_report(content: str, prefix: str = "report") -> Path:
    filename = f"{prefix}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    path = EXPORTS_DIR / filename
    path.write_text(content, encoding="utf-8")
    return path


def _append_executive_summary(lines: list[str], executive_summary: dict, severity_label: str) -> None:
    lines.append("EXECUTIVE SUMMARY")
    lines.append("-" * 78)
    if not executive_summary:
        lines.append(f"Overall status: {severity_label}")
        lines.append("No AI-generated executive summary is available for this analysis.")
        lines.append("")
        return

    lines.append(f"Status: {executive_summary.get('overall_status', severity_label)}")
    lines.append("")
    for wrapped in _wrap(executive_summary.get("summary_paragraph", ""), 74):
        lines.append(wrapped)
    lines.append("")
    lines.append(f"Top priority action: {executive_summary.get('top_priority_action', '')}")
    lines.append("")
    lines.append("Estimated business risk:")
    for wrapped in _wrap(executive_summary.get("estimated_business_risk", ""), 74):
        lines.append(f"  {wrapped}")
    lines.append("")

    steps = executive_summary.get("recommended_next_steps", [])
    if steps:
        lines.append("Prioritized next steps:")
        for idx, step in enumerate(steps, 1):
            lines.append(f"  {idx}. {step}")
    lines.append("")


def _append_top_recommendations(lines: list[str], recommendations: list[str]) -> None:
    lines.append("TOP RECOMMENDATIONS")
    lines.append("-" * 78)
    if not recommendations:
        lines.append("No prioritized recommendations were generated.")
    else:
        for idx, recommendation in enumerate(recommendations, 1):
            lines.append(f"{idx}. {recommendation}")
    lines.append("")


def _append_attack_timeline(lines: list[str], attack_timeline: list[dict[str, Any]]) -> None:
    if not attack_timeline:
        return
    lines.append("ATTACK TIMELINE")
    lines.append("-" * 78)
    for item in attack_timeline[:25]:
        lines.append(
            f"- {item.get('timestamp', 'unknown time')} | "
            f"{item.get('source_ip', 'unknown ip')} | "
            f"{item.get('threat_type', 'Unknown')} | "
            f"{item.get('method', '')} {item.get('path', '')} | "
            f"status={item.get('status', '')}"
        )
    lines.append("")


def _append_rule_pre_scan(lines: list[str], rule_findings: list[dict[str, Any]]) -> None:
    if not rule_findings:
        return
    lines.append("RULE-BASED PRE-SCAN SIGNALS")
    lines.append("-" * 78)
    for finding in rule_findings:
        confidence = int(float(finding.get("rule_confidence", finding.get("confidence", 0)) or 0) * 100)
        lines.append(
            f"- {finding.get('threat_type', 'Unknown')}: "
            f"{confidence}% confidence, pattern score {finding.get('pattern_score', 0)}, "
            f"{finding.get('owasp_category', 'N/A')}, MITRE {finding.get('mitre_attack_summary', 'N/A')}"
        )
        indicators = finding.get("indicator_hits", [])
        if indicators:
            lines.append(f"  Indicators: {', '.join(indicators[:5])}")
    lines.append("")


def _append_detailed_findings(lines: list[str], findings: list[dict[str, Any]]) -> None:
    lines.append("DETAILED FINDINGS")
    lines.append("-" * 78)

    if not findings:
        lines.append("No threats detected in the final analysis.")
        lines.append("")
        return

    for idx, finding in enumerate(findings, 1):
        severity = finding.get("severity", "Unknown")
        marker = SEVERITY_MARKERS.get(severity, "[WARN]")
        confidence = int(float(finding.get("confidence", 0) or 0) * 100)
        rule_conf = int(float(finding.get("rule_confidence", 0) or 0) * 100)

        lines.append(f"[FINDING #{idx}] {marker} {finding.get('threat_type', 'Unknown')}")
        lines.append(f"  Source      : {finding.get('analysis_source', 'Gemini AI')}")
        lines.append(f"  Severity    : {severity}")
        lines.append(f"  Confidence  : {confidence}% AI / {rule_conf}% rule")
        lines.append(f"  OWASP       : {finding.get('owasp_category', 'N/A')}")
        lines.append(f"  MITRE ATT&CK: {finding.get('mitre_attack_summary') or format_mitre_attack(finding.get('mitre_attack'))}")
        lines.append("")

        _append_wrapped_block(lines, "Evidence", finding.get("evidence", "N/A"))
        _append_wrapped_block(lines, "Explanation", finding.get("explanation", ""))
        _append_wrapped_block(lines, "Business Impact", finding.get("business_impact", ""))
        _append_wrapped_block(lines, "Immediate Fix", finding.get("immediate_fix", ""))
        _append_wrapped_block(lines, "Long-Term Fix", finding.get("long_term_fix", ""))
        _append_wrapped_block(lines, "Recommended Fix", finding.get("recommended_fix", ""))

        false_positive = finding.get("false_positive_note")
        if false_positive:
            _append_wrapped_block(lines, "False-Positive Note", false_positive)
        lines.append("-" * 78)


def _append_references(
    lines: list[str],
    findings: list[dict[str, Any]],
    rule_findings: list[dict[str, Any]],
) -> None:
    combined = (findings or []) + (rule_findings or [])
    if not combined:
        return

    lines.append("REFERENCES")
    lines.append("-" * 78)

    seen_owasp = set()
    for finding in combined:
        owasp = finding.get("owasp_category", "")
        for code, url in OWASP_LINKS.items():
            if code in owasp and code not in seen_owasp:
                lines.append(f"OWASP {code}: {url}")
                seen_owasp.add(code)

    seen_mitre = set()
    for finding in combined:
        mappings = finding.get("mitre_attack", []) or []
        if isinstance(mappings, dict):
            mappings = [mappings]
        if isinstance(mappings, str):
            mappings = []
        for mapping in mappings:
            technique_id = mapping.get("technique_id") if isinstance(mapping, dict) else ""
            if technique_id and technique_id not in seen_mitre:
                lines.append(f"MITRE {technique_id}: {_mitre_url(technique_id)}")
                seen_mitre.add(technique_id)
    lines.append("")


def _append_wrapped_block(lines: list[str], title: str, text: str) -> None:
    lines.append(f"  {title}:")
    if not text:
        lines.append("    N/A")
    else:
        for wrapped in _wrap(str(text), 70):
            lines.append(f"    {wrapped}")
    lines.append("")


def _wrap(text: str, width: int) -> list[str]:
    if not text:
        return [""]
    wrapped_lines: list[str] = []
    for paragraph in str(text).splitlines() or [""]:
        words = paragraph.split()
        if not words:
            wrapped_lines.append("")
            continue
        current: list[str] = []
        for word in words:
            current_length = sum(len(item) for item in current) + max(len(current) - 1, 0)
            if current and current_length + len(word) + 1 > width:
                wrapped_lines.append(" ".join(current))
                current = [word]
            else:
                current.append(word)
        if current:
            wrapped_lines.append(" ".join(current))
    return wrapped_lines or [""]


def _mitre_url(technique_id: str) -> str:
    parts = technique_id.replace("T", "").split(".")
    if len(parts) == 2:
        return f"https://attack.mitre.org/techniques/T{parts[0]}/{parts[1]}/"
    return f"https://attack.mitre.org/techniques/{technique_id}/"
